### ISSUE TITLE
play online with friends

### ISSUE THREAD

**Issue by m0ntelo** [kaimallea/csgo#10]
It is possible to make a server and play with friends?

I had a problem with my modem and could not release port 27015. Looking for a method to play on public ip lan

**Comment by kaimallea** [comment]
You can override the default port by passing `PORT` environment variable into the container. See https://github.com/kaimallea/csgo/blob/master/README.md#environment-variable-overrides

Have you tried this?

**Comment by kaimallea** [comment]
Feel free to re-open if you think that there is something more that can be done
