### ISSUE TITLE
Q: Interact with compose container

### ISSUE THREAD

**Issue by gardc** [kaimallea/csgo#16]
How do I interact with the server container spawned via docker compose? I want to type commands in the server console.

**Comment by kaimallea** [comment]
Hi, when you start the server with `docker-compose` you should detatch from it -- using `-d` or `--detatch`-- to send it to the background (e.g., `docker-compose up --detach`).

Then you can use `docker attach <container-id>` to attach to the container where you can type directly into the srcds console. Here's an example of me attaching and then typing `status` to see the server's status, followed by `meta version` to see the version of the Metamod's plugin:

**Important: you must use the keyboard combination `Ctrl+P, Ctrl+Q` to disconnect. If you use Ctrl+C you will be sending that to the srcds console which will stop the server**

![ScreenFlow](https://user-images.githubusercontent.com/228982/77179568-071e6c00-6a9f-11ea-880e-b3978a40f8de.gif)
