### ISSUE TITLE
Cant join server from my lan side.

### ISSUE THREAD

**Issue by nixeens** [kaimallea/csgo#17]
Friends can join from outside and works fine.
But i cant connect from my windows machine to cs go server.

**Comment by nixeens** [comment]
cant connect 0.0.0.0 my lan ip or localhost.
Also try this ip.
![image](https://user-images.githubusercontent.com/62589809/77476516-6673d780-6e23-11ea-9ce7-b38534cb47ef.png)

![image](https://user-images.githubusercontent.com/62589809/77476368-23b1ff80-6e23-11ea-9042-ac4536b3cc42.png)

`docker run --rm --interactive --tty --detach --mount source=csgo-data,target=/home/steam/csgo --publish 27015:27015/tcp --publish 27015:27015/udp --publish 27020:27020/tcp --publish 27020:27020/udp --env "SERVER_HOSTNAME=CSV GO PUBLIC OGAS" --env "SERVER_PASSWORD=" --env "RCON_PASSWORD=nix123" --env "STEAM_ACCOUNT=FF9XXXXXXXXXXXXXXXXXXXXXXXXXXXXX" --env "TICKRATE=128" --env "PORT=27015" --env "TV_PORT=27020" --env "MAPGROUP=mg_active" --env "TV_ENABLE=1" --env "IP=0.0.0.0" --env "LAN=0" --env "SOURCEMOD_ADMINS=STEAM_0:1:26725759,STEAM_1:1:225210097" kmallea/csgo`

**Comment by kaimallea** [comment]
What does it say in the console? `docker logs -f <container-id>`?

Also try specifying `IP` to be your actual IP instead of `0.0.0.0`. All zeros forces it to listen on all network interfaces, which should include the one with your actual IP.

Also, can you try using `--network=host` and remove all the `--publish` parameters? This will make all the ports in the container available to the host. It's possible others are needed to make it visible in the Steam server browser.

**Comment by kaimallea** [comment]
Also were you not able to manually type `connect <ip>` in your CSGO console rather than use the browser?

**Comment by nixeens** [comment]
if i use `--network=host` and add my local ip.

![image](https://user-images.githubusercontent.com/62589809/77826835-9d473780-711a-11ea-9aae-0a2502860aca.png)


`Setting mapgroup to 'mg_active'
NET_CloseAllSockets
WARNING: NET_OpenSocket: bind: Cannot assign requested address
Couldn't allocate any server IP port, tried 1 addresses 192.168.0.169Sat Mar 28 15:31:44 UTC 2020: Server restart in 10 seconds`

![image](https://user-images.githubusercontent.com/62589809/77827817-7ab81d00-7120-11ea-8dc7-67548d2e82f5.png)

**Comment by kaimallea** [comment]
@nixeens that error usually means that port is already in use. Make sure nothing else is running on your machine consuming the csgo port. Did you cleanup previous containers that used that port? `docker ps -a` can show you

**Comment by nixeens** [comment]
@kaimallea nothing there. Also used TCPview there is nothing with 27015 port on my host
![image](https://user-images.githubusercontent.com/62589809/77828498-78f05880-7124-11ea-9d38-6d824ec0bad6.png)

`nvcontainer.exe	4044	TCP	DESKTOP-G99CIDV	65001	DESKTOP-G99CIDV	0	LISTENING										
nvcontainer.exe	4044	TCP	DESKTOP-G99CIDV	65001	localhost	52089	ESTABLISHED										
nvcontainer.exe	12812	UDP	DESKTOP-G99CIDV	64378	*	*											
[System Process]	0	TCP	host.docker.internal	64335	40.122.160.14	https	TIME_WAIT	1	208	1	4 030						
[System Process]	0	TCP	host.docker.internal	64301	172.93.108.170	https	TIME_WAIT										
[System Process]	0	TCP	host.docker.internal	64292	a104-97-8-10.deploy.static.akamaitechnologies.com	https	TIME_WAIT										
[System Process]	0	TCP	host.docker.internal	64289	dlinkrouter.dlink	http	TIME_WAIT										
[System Process]	0	TCP	host.docker.internal	64288	dlinkrouter.dlink	http	TIME_WAIT										
[System Process]	0	TCP	host.docker.internal	64286	dlinkrouter.dlink	http	TIME_WAIT										
[System Process]	0	TCP	host.docker.internal	64281	dlinkrouter.dlink	http	TIME_WAIT										
[System Process]	0	TCP	host.docker.internal	64279	dlinkrouter.dlink	http	TIME_WAIT										
[System Process]	0	TCP	host.docker.internal	64273	dlinkrouter.dlink	http	TIME_WAIT										
[System Process]	0	TCP	host.docker.internal	64270	dlinkrouter.dlink	http	TIME_WAIT										
[System Process]	0	TCP	host.docker.internal	64266	dlinkrouter.dlink	http	TIME_WAIT										
chrome.exe	2516	TCP	host.docker.internal	64245	151.101.84.133	https	ESTABLISHED										
chrome.exe	2516	TCP	host.docker.internal	64134	40.77.226.250	https	ESTABLISHED										
[System Process]	0	TCP	host.docker.internal	64129	a104-122-250-9.deploy.static.akamaitechnologies.com	http	TIME_WAIT										
chrome.exe	2516	TCP	host.docker.internal	64090	104.16.30.34	https	ESTABLISHED										
chrome.exe	2516	TCP	host.docker.internal	64087	151.101.1.69	https	ESTABLISHED										
chrome.exe	2516	TCP	host.docker.internal	63753	lb-140-82-114-26-iad.github.com	https	ESTABLISHED	1	28	1	24						
chrome.exe	2516	TCP	host.docker.internal	63644	216.218.159.29	https	ESTABLISHED	8	1 140	11	1 710						
chrome.exe	2516	TCP	host.docker.internal	63618	lq-in-f188.1e100.net	5228	ESTABLISHED										
chrome.exe	2516	TCP	host.docker.internal	63605	lb-140-82-114-26-iad.github.com	https	ESTABLISHED	1	28	1	24						
chrome.exe	2516	TCP	host.docker.internal	63604	lb-140-82-114-26-iad.github.com	https	ESTABLISHED	1	28	1	24						
svchost.exe	2304	TCP	host.docker.internal	63592	51.105.249.223	https	ESTABLISHED										
com.docker.proxy.exe	14424	TCP	DESKTOP-G99CIDV	62164	DESKTOP-G99CIDV	0	LISTENING										
svchost.exe	9760	UDPV6	desktop-g99cidv	59732	*	*											
svchost.exe	9760	UDP	DESKTOP-G99CIDV	59731	*	*											
svchost.exe	9760	UDP	DESKTOP-G99CIDV	59730	*	*											
com.docker.proxy.exe	14424	UDP	DESKTOP-G99CIDV	57326	*	*											
nvcontainer.exe	4044	UDPV6	desktop-g99cidv	52743	*	*											
nvcontainer.exe	4044	UDP	DESKTOP-G99CIDV	52742	*	*											
svchost.exe	8	TCP	DESKTOP-G99CIDV	52700	DESKTOP-G99CIDV	0	LISTENING										
svchost.exe	8	TCPV6	desktop-g99cidv	52700	desktop-g99cidv	0	LISTENING										
eidLvUI.exe	14100	TCP	DESKTOP-G99CIDV	52231	DESKTOP-G99CIDV	0	LISTENING										
NVIDIA Web Helper.exe	16792	TCP	DESKTOP-G99CIDV	52121	DESKTOP-G99CIDV	0	LISTENING										
nvcontainer.exe	4044	TCP	DESKTOP-G99CIDV	52089	localhost	65001	ESTABLISHED										
svchost.exe	16672	UDP	desktop-g99cidv.mshome.net	52022	*	*											
svchost.exe	16672	UDP	DESKTOP-G99CIDV	52021	*	*											
svchost.exe	16672	UDP	host.docker.internal	52020	*	*											
svchost.exe	16672	UDPV6	[fe80:0:0:0:6c6e:eb7:8a18:4433]	52019	*	*											
svchost.exe	16672	UDPV6	[0:0:0:0:0:0:0:1]	52018	*	*											
svchost.exe	16672	UDPV6	[fe80:0:0:0:e5ab:8a41:b28d:e4e5]	52017	*	*											
services.exe	964	TCP	DESKTOP-G99CIDV	49676	DESKTOP-G99CIDV	0	LISTENING										
services.exe	964	TCPV6	desktop-g99cidv	49676	desktop-g99cidv	0	LISTENING										
CueLLAccessService.exe	3984	TCP	DESKTOP-G99CIDV	49674	DESKTOP-G99CIDV	0	LISTENING										
jhi_service.exe	4412	TCPV6	[0:0:0:0:0:0:0:1]	49672	desktop-g99cidv	0	LISTENING										
spoolsv.exe	3544	TCP	DESKTOP-G99CIDV	49670	DESKTOP-G99CIDV	0	LISTENING										
spoolsv.exe	3544	TCPV6	desktop-g99cidv	49670	desktop-g99cidv	0	LISTENING										
svchost.exe	1776	TCP	DESKTOP-G99CIDV	49667	DESKTOP-G99CIDV	0	LISTENING										
svchost.exe	1776	TCPV6	desktop-g99cidv	49667	desktop-g99cidv	0	LISTENING										
svchost.exe	1676	TCP	DESKTOP-G99CIDV	49666	DESKTOP-G99CIDV	0	LISTENING										
svchost.exe	1676	TCPV6	desktop-g99cidv	49666	desktop-g99cidv	0	LISTENING										
wininit.exe	892	TCP	DESKTOP-G99CIDV	49665	DESKTOP-G99CIDV	0	LISTENING										
wininit.exe	892	TCPV6	desktop-g99cidv	49665	desktop-g99cidv	0	LISTENING										
lsass.exe	992	TCP	DESKTOP-G99CIDV	49664	DESKTOP-G99CIDV	0	LISTENING										
lsass.exe	992	TCPV6	desktop-g99cidv	49664	desktop-g99cidv	0	LISTENING										
svchost.exe	3884	UDP	DESKTOP-G99CIDV	49415	*	*											
NVIDIA Web Helper.exe	16792	UDP	DESKTOP-G99CIDV	10020	*	*											
svchost.exe	2352	TCP	DESKTOP-G99CIDV	ms-do	DESKTOP-G99CIDV	0	LISTENING										
svchost.exe	2352	TCPV6	desktop-g99cidv	ms-do	desktop-g99cidv	0	LISTENING										
svchost.exe	2276	UDP	DESKTOP-G99CIDV	llmnr	*	*											
svchost.exe	2276	UDPV6	desktop-g99cidv	5355	*	*											
chrome.exe	13240	UDP	DESKTOP-G99CIDV	5353	*	*											
svchost.exe	2276	UDP	DESKTOP-G99CIDV	5353	*	*											
chrome.exe	13240	UDP	DESKTOP-G99CIDV	5353	*	*											
nvcontainer.exe	4044	UDP	desktop-g99cidv.mshome.net	5353	*	*											
nvcontainer.exe	4044	UDP	host.docker.internal	5353	*	*											
chrome.exe	13240	UDP	DESKTOP-G99CIDV	5353	*	*											
chrome.exe	13240	UDP	DESKTOP-G99CIDV	5353	*	*											
chrome.exe	13240	UDPV6	desktop-g99cidv	5353	*	*											
chrome.exe	13240	UDPV6	desktop-g99cidv	5353	*	*											
svchost.exe	2276	UDPV6	desktop-g99cidv	5353	*	*											
nvcontainer.exe	4044	UDPV6	[0:0:0:0:0:0:0:1]	5353	*	*											
svchost.exe	6984	UDP	DESKTOP-G99CIDV	5050	*	*											
svchost.exe	6984	TCP	DESKTOP-G99CIDV	5040	DESKTOP-G99CIDV	0	LISTENING										
svchost.exe	14016	UDP	DESKTOP-G99CIDV	ipsec-msft	*	*											
svchost.exe	14016	UDPV6	desktop-g99cidv	4500	*	*											
vmms.exe	4108	TCP	DESKTOP-G99CIDV	2179	DESKTOP-G99CIDV	0	LISTENING										
vmms.exe	4108	TCPV6	desktop-g99cidv	2179	desktop-g99cidv	0	LISTENING										
svchost.exe	3936	UDP	desktop-g99cidv.mshome.net	qwave	*	*											
svchost.exe	3936	UDP	host.docker.internal	qwave	*	*											
svchost.exe	3936	UDPV6	[fe80:0:0:0:6c6e:eb7:8a18:4433]	2177	*	*											
svchost.exe	3936	UDPV6	[fe80:0:0:0:e5ab:8a41:b28d:e4e5]	2177	*	*											
svchost.exe	16672	UDP	DESKTOP-G99CIDV	ssdp	*	*				8	3 498						
svchost.exe	16672	UDP	desktop-g99cidv.mshome.net	ssdp	*	*											
svchost.exe	16672	UDP	host.docker.internal	ssdp	*	*											
svchost.exe	16672	UDPV6	[0:0:0:0:0:0:0:1]	1900	*	*											
svchost.exe	16672	UDPV6	[fe80:0:0:0:6c6e:eb7:8a18:4433]	1900	*	*											
svchost.exe	16672	UDPV6	[fe80:0:0:0:e5ab:8a41:b28d:e4e5]	1900	*	*											
svchost.exe	14016	UDP	DESKTOP-G99CIDV	isakmp	*	*											
svchost.exe	14016	UDPV6	desktop-g99cidv	500	*	*											
System	4	TCP	DESKTOP-G99CIDV	microsoft-ds	DESKTOP-G99CIDV	0	LISTENING										
System	4	TCPV6	desktop-g99cidv	microsoft-ds	desktop-g99cidv	0	LISTENING										
System	4	TCP	desktop-g99cidv.mshome.net	netbios-ssn	DESKTOP-G99CIDV	0	LISTENING										
System	4	TCP	host.docker.internal	netbios-ssn	DESKTOP-G99CIDV	0	LISTENING										
System	4	UDP	desktop-g99cidv.mshome.net	netbios-dgm	*	*											
System	4	UDP	host.docker.internal	netbios-dgm	*	*											
System	4	UDP	desktop-g99cidv.mshome.net	netbios-ns	*	*											
System	4	UDP	host.docker.internal	netbios-ns	*	*											
svchost.exe	1200	TCP	DESKTOP-G99CIDV	epmap	DESKTOP-G99CIDV	0	LISTENING										
svchost.exe	1200	TCPV6	desktop-g99cidv	epmap	desktop-g99cidv	0	LISTENING										
svchost.exe	8508	UDP	DESKTOP-G99CIDV	ntp	*	*											
svchost.exe	8508	UDPV6	desktop-g99cidv	123	*	*											
svchost.exe	9760	UDP	desktop-g99cidv.mshome.net	bootpc	*	*											
svchost.exe	9760	UDP	desktop-g99cidv.mshome.net	bootps	*	*											
svchost.exe	9760	UDP	DESKTOP-G99CIDV	domain	*	*											
`

**Comment by kaimallea** [comment]
Interesting. Windows Firewall blocking outbound traffic on those udp/tcp ports perhaps?

**Comment by nixeens** [comment]
Turner windows firewall off didnt help. with bridge network its working with --publish 27016 i can get in and also friends from public ip. For now im ok with publish.
