### ISSUE TITLE
how to access csgo-data volume or containerfs

### ISSUE THREAD

**Issue by nixeens** [kaimallea/csgo#18]
Im kinda new to docker-desktop. I cant i can't figure it out how to add files to containerfs. I want to add some new maps and in future some cfg addons. Im using Windows with docker-desktop and PS.
![image](https://user-images.githubusercontent.com/62589809/77790430-81398c80-706d-11ea-98c1-9a334461b11d.png)

tryed docker cp C:/test CSGOTEST:/containerfs
still nothing ;( can i get some tip? waisted all day with this

**Comment by kaimallea** [comment]
`containerfs` isn't a real location, it's a temporary build time folder that copies its contents into `/home/steam/csgo/csgo/`. That latter path is where the CSGO folder lives in the container.

For your case, you can use something like `docker cp practice.cfg:/home/steam/csgo/csgo/cfg/` to copy `practice.cfg` into your container.

I'm also about to publish a change that lets you use a bind volume, which might be easier to manage.

**Comment by kaimallea** [comment]
Also, wrap your paths in quotes if they contain spaces or weird characters.

**Comment by nixeens** [comment]
Great with new bind volume i can easly add some files, but i got other problem. I dont know why sourceadmin addon dosnt load up. Meta list works so but sourceadmin dosnt work

> L 03/28/2020 - 18:03:28: [META] Loaded 0 plugins.

**Comment by kaimallea** [comment]
When the container starts up it downloads plugins if they don’t already exist. Check the output of the running container to see if there was an error while downloading. Restarting the container will make it try again.

`docket logs -f <id>` will follow the output as it runs

**Comment by nixeens** [comment]
Dosnt see anything wrong.
Also there is vdf files
![image](https://user-images.githubusercontent.com/62589809/77831200-6ed75580-7136-11ea-86a8-1af06597f280.png)
![image](https://user-images.githubusercontent.com/62589809/77831212-7c8cdb00-7136-11ea-9221-3d4ffca980e4.png)
gona try add manually.
[CSVGOLOG.TXT](https://github.com/kaimallea/csgo/files/4397677/CSVGOLOG.TXT)

**Comment by nixeens** [comment]
maybe there is something wrong with my docker run code?
`docker run --rm --interactive --tty --detach --name CSVGO --mount type=bind,source=$(pwd),target=/home/steam/csgo --publish 27016:27016/tcp --publish 27016:27016/udp --publish 27020:27020/tcp --publish 27020:27020/udp --env "SERVER_HOSTNAME=CSV GO PUBLIC LAT" --env "SERVER_PASSWORD=" --env "RCON_PASSWORD=XXXX" --env "STEAM_ACCOUNT=FF9XXXXXXXXXXXXXXXXXXXXXXXX" --env "TICKRATE=128" --env "PORT=27016" --env "TV_PORT=27020" --env "MAPGROUP=mg_active" --env "TV_ENABLE=0" --env IP="172.17.0.2" --env "LAN=0" --env "SOURCEMOD_ADMINS=STEAM_0:1:26725759,STEAM_1:1:225210097" kmallea/csgo:latest`

**Comment by nixeens** [comment]
L 03/28/2020 - 19:21:04: [META] Loaded 1 plugin.
add manually sourcemode and metamod and works fine. Thats all, ty
