### ISSUE TITLE
Error! App '740' state is 0x202 after update job.

### ISSUE THREAD

**Issue by christiansenandi** [kaimallea/csgo#30]
Hi,

i am stuck at this error when trying to run it for the first time, i know it means out of space but i have mounted a volume of 40G on /home/steam which is dedicated to this instance and i still get this error?

Do you know how to get it running?

its a small vps with only 20G total space available and a data volume mounted on /home/steam

Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '740' state is 0x202 after update job.

root@csgo-server:/home# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            968M     0  968M   0% /dev
tmpfs           196M  3.1M  193M   2% /run
/dev/sda1        19G  1.8G   17G  10% /
tmpfs           976M     0  976M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           976M     0  976M   0% /sys/fs/cgroup
/dev/sda15       61M  121K   60M   1% /boot/efi
tmpfs           196M     0  196M   0% /run/user/0
/dev/sdb         40G   49M   38G   1% /home/steam

Thanks

**Comment by christiansenandi** [comment]
Ended up just upgrading the vps main disk and now its updating just fine :)

Sorry for bothering ;)

**Comment by kaimallea** [comment]
Glad you got it working! The mount point for volumes is `/home/steam/csgo`
