### ISSUE TITLE
128 Tick not working

### ISSUE THREAD

**Issue by greinet** [kaimallea/csgo#33]
Hey,

I can get the server running without problems via docker-compose, but the server always displays 64 tick, even though I configured 128 tick in the docker-compose (left the default value there). I also have a lot of yellow/red numbers when using net_graph ingame which might be part of the problem. 

Any ideas on whats causing the problems or how to debug/test whats going on?

**Comment by 0BuRner** [comment]
Hello, can you give a screenshot/short video of your net_graph ? Is it most of the time red/orange or only sometimes during short duration ?

**Comment by greinet** [comment]
Sorry I can`t make a video right now but it basically jumps between yellow, orange and red all the time. I guess thats just a performance issue on my side as i tried a different servers und got better results with a more powerfull one. But my main problem here is still that I can't get 128 ticks working. Could this be caused by a too slow server?

**Comment by 0BuRner** [comment]
That's what I think, but I'm not sure...

**Comment by greinet** [comment]
When running the server on my main pc via Docker for Windows with nearly 0 sv on net_graph I still can't get 128 tick working. Is there anything wrong with my configuration?

[compose.txt](https://github.com/kaimallea/csgo/files/4638428/compose.txt)
(Sorry had no idea how to keep the spaces when adding the yml so i just added the file)

**Comment by greinet** [comment]
I finally got 128tick working by editing start.sh and adding following settings to the part where the server.cfg is dynamically created:

sv_maxrate 0
sv_minrate 80000
sv_mincmdrate 128
sv_maxupdaterate 128
sv_minupdaterate 128

**Comment by kaimallea** [comment]
Fixed by #48
