### ISSUE TITLE
mkdir: cannot create directory ‘/home/steam/csgo/csgo’: Permission denied

### ISSUE THREAD

**Issue by MyFaith** [kaimallea/csgo#38]
mkdir: cannot create directory ‘/home/steam/csgo/csgo’: Permission denied
grep: /home/steam/csgo/srcds_run: No such file or directory
/bin/bash: /home/steam/csgo/srcds_run: No such file or directory

I have use volume
```
docker run \
  --rm \
  --interactive \
  --tty \
  --detach \
  -v /home/csgo/data:/home/steam/csgo \
  --network=host \
  --env "SERVER_HOSTNAME=hostname" \
  --env "SERVER_PASSWORD=password" \
  --env "RCON_PASSWORD=rconpassword" \
  --env "STEAM_ACCOUNT=gamelogintoken" \
  --env "AUTHKEY=webapikey" \
  --env "SOURCEMOD_ADMINS=STEAM_1:0:123456,STEAM_1:0:654321" \
  kmallea/csgo
```

**Comment by 0BuRner** [comment]
Did you set appropriate access rights on folder /home/csgo/data on your host machine ?

**Comment by MyFaith** [comment]
yes, im trying to use --user but it faild too.
