### ISSUE TITLE
Metamod/Sourcemod broken

### ISSUE THREAD

**Issue by Soren90** [kaimallea/csgo#64]
Hello,

It seems like the versions of metamod/sourcemod in this repo makes the server coredump on startup in the current state.  

```/home/steam/csgo/srcds_run: line 318: 294 aborted (core dumped) $hl_cmd```

When I removed the addons/metamod folder the server starts up as expected. I'll try to update metamod/sourcemod and see if I can get it to work

**Comment by Soren90** [comment]
I was able to solve this issue by updating metamod and sourcemod. Seems to be working fine after some light testing

**Comment by kaimallea** [comment]
Thanks, I plan on revisiting and updating this repo soon. Life got in the way. 😄

**Comment by Soren90** [comment]
> Thanks, I plan on revisiting and updating this repo soon. Life got in the way. smile

Sounds good! Let me know if I can help you out :)
